In [1]:
import numpy as np

In [4]:
redis_acts = []


In [20]:
for i in redispatch_acts:
    redis_acts.append(i.to_vect())

In [21]:
redis_acts

[array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1

In [5]:
import grid2op
from grid2op import make

env = make('l2rpn_wcci_2022')
obs = env.reset()

error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))


In [19]:
def get_available_dispatch_actions( observation):
    action_array = []
    max_up = env.action_space.gen_max_ramp_up
    max_down = env.action_space.gen_max_ramp_down
    for i in range(len(max_up)):
        if max_up[i] != 0:
            action = env.action_space({"redispatch": [(i, -max_down[i])]})
            action_array.append(action)
            action = env.action_space({"redispatch": [(i, +max_up[i])]})
            action_array.append(action)
            
            
            action = env.action_space({"redispatch": [(i, -max_down[i]/4)]})
            action_array.append(action)
            action = env.action_space({"redispatch": [(i, +max_up[i]/4)]})
            action_array.append(action)
    return action_array

In [20]:
redispat_act = get_available_dispatch_actions(obs)

In [21]:
obs = env.reset()

In [22]:
len(redispat_act)

80

In [23]:
redis_acts = []

In [24]:
for i in redispat_act:
    redis_acts.append(i.to_vect())

In [25]:
len(redis_acts)

80

In [26]:
import pickle

file_in = open('redispatch_vect_full_by_four.pickle', 'wb')
pickle.dump(redis_acts, file_in)
file_in.close()

In [32]:
aa = env.action_space.from_vect(redis_acts[0])

In [44]:
aa.as_serializable_dict()['redispatch'][0][0]

2

In [6]:
import grid2op
from grid2op import make

env = make('l2rpn_wcci_2022')

a = env.action_space({})

In [8]:
for i in redis_acts:
    k = a + env.action_space.from_vect(i)
    
    print(k)
    sys.exit()

This action will:
	 - NOT change anything to the injections
	 - Modify the generators with redispatching in the following way:
	 	 - Redispatch "gen_7_2" of -1.75 MW
	 - NOT modify any storage capacity
	 - NOT perform any curtailment
	 - NOT force any line status
	 - NOT switch any line status
	 - NOT switch anything in the topology
	 - NOT force any particular bus configuration


NameError: name 'sys' is not defined

In [1]:
import numpy as np

In [2]:
np.load('redispatch_vect_full.pickle', allow_pickle=True)

[array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1.], dtype=float32),
 array([ 0.,  0.,  0., ..., -1., -1., -1

In [3]:
import numpy as np

In [6]:
len(np.load('redispatch_vect.pickle', allow_pickle=True))

120